name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
    paths:
      - 'schemas/**'
      - 'static-site/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Build the static site and deploy to pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Init nodejs
        uses: ./.github/actions/init-npm

      - name: Build website
        run: npm run build
        working-directory: ./static-site

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./static-site/dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          folder: ./static-site/dist # The folder the action should deploy.
          clean-exclude: pr-preview/
          force: false
